-- Enable uuid-ossp extension for robust unique IDs, though Supabase Auth uses UUIDs natively natively
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================================
-- 1. Custom Types (Enums) for Strict Data Integrity
-- ============================================================================
CREATE TYPE plan_type AS ENUM ('free', 'pro', 'agency');
CREATE TYPE scan_trigger AS ENUM ('user', 'cron', 'system');
CREATE TYPE scan_status AS ENUM ('pending', 'running', 'completed', 'target_failed');
CREATE TYPE check_status AS ENUM ('pass', 'fail', 'warning', 'info');
CREATE TYPE severity_level AS ENUM ('low', 'medium', 'high', 'critical', 'info');
CREATE TYPE alert_type AS ENUM ('malware', 'domain_expiring', 'new_port', 'breach_detected');

-- ============================================================================
-- 2. Core Tables mapped against your Python SQLModel schema
-- ============================================================================

-- Users Table (Hooks into Supabase internal Auth via auth.users)
CREATE TABLE public.users (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    plan plan_type DEFAULT 'free'::plan_type NOT NULL,
    stripe_customer_id VARCHAR(255) UNIQUE,
    stripe_subscription_id VARCHAR(255) UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Domains Table (What the user is monitoring)
CREATE TABLE public.domains (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    domain VARCHAR(255) NOT NULL,
    verified_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, domain) -- Prevent users from adding the same domain twice
);

-- Scans Table (History of scans executed against a domain)
CREATE TABLE public.scans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_id BIGINT REFERENCES public.domains(id) ON DELETE CASCADE NOT NULL,
    triggered_by scan_trigger DEFAULT 'user'::scan_trigger NOT NULL,
    status scan_status DEFAULT 'pending'::scan_status NOT NULL,
    ai_remediation_summary TEXT, -- Stores the Groq AI output for the dashboard
    pdf_report_url TEXT, -- Stores the URL of the generated WeasyPrint Arabic PDF
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE
);

-- Scan Results Table (Individual vulnerability checks inside a scan)
CREATE TABLE public.scan_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_id BIGINT REFERENCES public.scans(id) ON DELETE CASCADE NOT NULL,
    check_name VARCHAR(255) NOT NULL,
    status check_status NOT NULL,
    severity severity_level NOT NULL,
    detail TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Alerts Table (For the Weekly Cron Job email dispatching trigger)
CREATE TABLE public.alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain_id BIGINT REFERENCES public.domains(id) ON DELETE CASCADE NOT NULL,
    type alert_type NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ============================================================================
-- 3. Row Level Security (RLS) Policies
-- These ensure that a user can ONLY see their own domains, scans, and alerts
-- ============================================================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.domains ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scan_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;

-- User Policies
CREATE POLICY "Users can view their own profile" 
    ON public.users FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update their own profile" 
    ON public.users FOR UPDATE USING (auth.uid() = id);

-- Domain Policies
CREATE POLICY "Users can manage their own domains" 
    ON public.domains FOR ALL USING (auth.uid() = user_id);

-- Scan Policies (Slightly more complex since they map through domains)
CREATE POLICY "Users can view scans for their domains" 
    ON public.scans FOR SELECT USING (
        domain_id IN (SELECT id FROM public.domains WHERE user_id = auth.uid())
    );

CREATE POLICY "Users can insert scans for their domains" 
    ON public.scans FOR INSERT WITH CHECK (
        domain_id IN (SELECT id FROM public.domains WHERE user_id = auth.uid())
    );

-- Scan Result Policies
CREATE POLICY "Users can view scan results for their domains" 
    ON public.scan_results FOR SELECT USING (
        scan_id IN (
            SELECT id FROM public.scans WHERE domain_id IN (
                SELECT id FROM public.domains WHERE user_id = auth.uid()
            )
        )
    );

-- Alert Policies
CREATE POLICY "Users can view and manage alerts for their domains" 
    ON public.alerts FOR ALL USING (
        domain_id IN (SELECT id FROM public.domains WHERE user_id = auth.uid())
    );

-- ============================================================================
-- 4. Supabase Auth Trigger
-- Automatically create a NextLab 'public.users' entry when a user signs up on the frontend
-- ============================================================================

CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.users (id, email, plan)
    VALUES (new.id, new.email, 'free');
    RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ============================================================================
-- 5. Indexes for Performance (Scaling SaaS read operations)
-- ============================================================================
CREATE INDEX idx_domains_user_id ON public.domains(user_id);
CREATE INDEX idx_scans_domain_id ON public.scans(domain_id);
CREATE INDEX idx_scan_results_scan_id ON public.scan_results(scan_id);
CREATE INDEX idx_alerts_domain_id ON public.alerts(domain_id);
